spring:
  application:
    name: comms-service
  config:
    import: "optional:file:/app/config/application-secrets.yml"
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 9110
  forward-headers-strategy: framework
  servlet:
   context-path: /

logging:
  file:
    name:  # Leave blank so logs go to stdout
  level:
    root: INFO
    za.co.k-polit.comms: DEBUG
  pattern:
    console: '{"timestamp": "%d{yyyy-MM-dd HH:mm:ss}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'

springdoc:
  api-docs:
    # Expose your OpenAPI JSON at /v3/api-docs
    path: /v3/api-docs
  swagger-ui:
    # Expose Swagger UI at /swagger-ui.html
    path: /swagger-ui.html
    # Force Swagger UI to use the correct docs URL
    url: /v3/api-docs
    # (Optional) Nice name in the Swagger header
    display-operation-id: true
    doc-expansion: none
eureka:
  instance:
    hostname: host.containers.internal #localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/